### ISSUE TITLE
safari 兼容问题

### ISSUE THREAD

**Issue by bison1994** [itouzigithub/experience-mobile#4]
1. 用书面语，确保语句通顺，无歧义，尽可能简练
2. 清楚的描述问题场景，缺乏上下文信息会导致读者一头雾水
3. 给出解决方案或使用建议
4. 用 markdown 组织格式

**Comment by HippocampalAbnormality** [comment]
for in遍历对象问题：高程写safari3及以下浏览器会出现对象遍历个别属性出现两次问题，真机中iphone6、6s都出现了。

**Comment by HippocampalAbnormality** [comment]
ios 上，animation 动画直接渲染会有很高几率卡住无效，或者直接不显示等各种问题，一个解决方案是animation 加延时执行

**Comment by bison1994** [comment]
iphone6 上直接用 `element.style = '...'` 的方式修改样式会报错：can't modify readonly property.
解决办法是用 `setAttribute('style')`

**Comment by bison1994** [comment]
`user-scalable=no` 在 IOS10 上是没用的，用户总是可以缩放，这个客户端故意这么设计的

**Comment by bison1994** [comment]
[safari 动画失效的一些可能的解决方案](https://stackoverflow.com/questions/9211261/css3-animation-not-working-in-safari)

**Comment by bison1994** [comment]
对于 safari，使用 CSS3 动画时必须保证每个属性值都“一致”，不能有缺省值。
比如这样是不行的，transform 的属性值“不一致”：
```css
@keyframes heart {
  0% {
    transform: scale(0);
  }
  15% {
    transform: scale(1);
  }
  40% {
    transform: translate3d(-300%, -200%, 0) rotate(-10deg);
  }
  100% {
    transform: translate3d(-900%, -500%, 0) rotate(10deg);
  }
}
```
必须改成“一致”：
```css
@keyframes heart {
  0% {
    transform: translate3d(0, 0, 0) rotate(0) scale(0);
  }
  15% {
    transform: translate3d(0, 0, 0) rotate(0) scale(1);
  }
  40% {
    transform: translate3d(-300%, -200%, 0) rotate(-10deg) scale(1);
  }
  100% {
    transform: translate3d(-900%, -500%, 0) rotate(10deg) scale(1);
  }
}
```
