### ISSUE TITLE
IOS 浏览器兼容问题

### ISSUE THREAD

**Issue by bison1994** [itouzigithub/experience-mobile#8]
包括：safari 和 webview

**Comment by HippocampalAbnormality** [comment]
### ios opacity 和 box-shadow 在 animation 中共用时会有闪烁的问题
```css
@keyframes animation {
    0% {
        box-shadow: 0 0 0 0 #0bcaf3;
        opacity: 1;
    }
    100% {
        box-shadow: 0 0 0 10px #0bcaf3;
        opacity: 0;
    }
}
```
现象：安卓正常，ios 出现闪烁问题
解决方案：避免二者共存，box-shadow 的颜色用 rgba，让 alpha 从 1 过渡到 0

**Comment by bison1994** [comment]
IOS 浏览器背景纯色渐变如果包含透明度（例如从某种颜色渐变至透明），写成这样是无法正确渲染的：
```css
background-image: linear-gradient(to bottom, rgb(17, 9, 62) 0%, transparent 100%)
or
background-image: linear-gradient(to bottom, rgb(17, 9, 62) 0%, rgba(0, 0, 0, 0) 100%)
```
应该写成这样：
```css
background-image: linear-gradient(to bottom, rgba(17, 9, 62, 1) 0%, rgba(17, 9, 62, 0) 100%)
```

**Comment by bison1994** [comment]
在 IOS 中如果 transform 动画出现闪烁，通常的解决方案是：
```css
backface-visibility: hidden;
transform-style: preserve-3d;
```
但是，如果父子元素均设置 transform + transition 动画，即便都设置了上述代码，仍会出现闪烁。
```html
<div class="transform-1 transition-1">
    <div class="transform-2 transition-2></div>
</div>
```
解决方案一：去掉子元素的 transition。可以避免闪烁，但失去了动画的渐变效果
解决方案二：子元素不要用 transform 做动画，用 width、height、margin 之类的普通属性代替 transform

**Comment by bison1994** [comment]
#### 身份证输入框的类型应该为 text
如果为了调出数字键盘，就将输入框类型设为 number，会导致输入尾数为 x 的身份证号时，`input.value` 无法取到最后的字母。
在 chrome 和安卓浏览器中，无法向数字型输入框输入字母或其它与数字无关的符号（可以输入点号、加号、减号等），但是在妖孽的 safari 中，可以向数字型输入框输入任何值。而一旦输入非数字字符，可能导致 `input.value` 直接变为空字符串

**Comment by bison1994** [comment]
对于 safari，使用 CSS3 动画时必须保证每个属性值都“一致”，不能有缺省值。
比如这样是不行的，transform 的属性值“不一致”：
```css
@keyframes heart {
  0% {
    transform: scale(0);
  }
  15% {
    transform: scale(1);
  }
  40% {
    transform: translate3d(-300%, -200%, 0) rotate(-10deg);
  }
  100% {
    transform: translate3d(-900%, -500%, 0) rotate(10deg);
  }
}
```
必须改成“一致”：
```css
@keyframes heart {
  0% {
    transform: translate3d(0, 0, 0) rotate(0) scale(0);
  }
  15% {
    transform: translate3d(0, 0, 0) rotate(0) scale(1);
  }
  40% {
    transform: translate3d(-300%, -200%, 0) rotate(-10deg) scale(1);
  }
  100% {
    transform: translate3d(-900%, -500%, 0) rotate(10deg) scale(1);
  }
}
```
